version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t terribledev/public:remote-latest src/aka.terribledev.io
     - run: docker build -t terribledev/public:remote-$CIRCLE_SHA1 src/aka.terribledev.io

     # deploy the image
     - run: docker push terribledev/public:remote-latest
     - run: docker push terribledev/public:remote-$CIRCLE_SHA1